version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./app-config/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: [ "uvicorn", "djangoapp.asgi:application", "--workers","1", "--host", "0.0.0.0","--port", "3000" ]
